import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

interface Route {
  name: string;
  link: string;
  image: string;
}

const routeList = [
  {
    name: 'Home',
    link: '/',
    image: 'https://cdn-icons-png.flaticon.com/512/3670/3670147.png'
  },
  {
    name: 'Crawler',
    link: '/crawler',
    image: 'https://cdn-icons-png.flaticon.com/512/9850/9850830.png'
  },
  {
    name: 'Scheduler',
    link: '/scheduler',
    image: 'https://cdn-icons-png.flaticon.com/512/9850/9850830.png'
  },
  {
    name: 'ImageCaption',
    link: '/imagecaption',
    image: 'https://cdn-icons-png.flaticon.com/512/9850/9850830.png'
  }
]

function RouteElement({ route }: { route: Route }) {
  const { name, link, image } = route
  return (
    <Link className="route-element" href={link}>
      <img src={image} />
      <div className="title">{name}</div>
    </Link>
  )
}

function RouteList({ routeList } : { routeList: Route[] }) {
  const RouteLogo = () => {
    return (
      <div className="route-logo">
        <div className="title">ChrisSu</div>
      </div>
    )
  }
  return (
    <div className="route-list">
      <RouteLogo />
      {routeList.map((route, idx) => (
        <RouteElement key={idx} route={route} />
      ))}
    </div>
  )
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <RouteList routeList={routeList} />
        <div className="main-container">
          {children}
        </div>
      </body>
    </html>
  );
}
